//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCC_GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCC_GUI.Languages.Language_en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert files.
        /// </summary>
        internal static string ConvertFiles {
            get {
                return ResourceManager.GetString("ConvertFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text.
        /// </summary>
        internal static string ConvertText {
            get {
                return ResourceManager.GetString("ConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong to Simplified.
        /// </summary>
        internal static string hk2s {
            get {
                return ResourceManager.GetString("hk2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load....
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified to Hong Kong.
        /// </summary>
        internal static string s2hk {
            get {
                return ResourceManager.GetString("s2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified to Traditional.
        /// </summary>
        internal static string s2t {
            get {
                return ResourceManager.GetString("s2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified to Taiwan.
        /// </summary>
        internal static string s2tw {
            get {
                return ResourceManager.GetString("s2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified to Taiwan with Taiwanese idiom.
        /// </summary>
        internal static string s2twp {
            get {
                return ResourceManager.GetString("s2twp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &amp;&amp; &amp;Save....
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files....
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional to Hong Kong.
        /// </summary>
        internal static string t2hk {
            get {
                return ResourceManager.GetString("t2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional to Simplified.
        /// </summary>
        internal static string t2s {
            get {
                return ResourceManager.GetString("t2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional to Taiwan.
        /// </summary>
        internal static string t2tw {
            get {
                return ResourceManager.GetString("t2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan to Simplified.
        /// </summary>
        internal static string tw2s {
            get {
                return ResourceManager.GetString("tw2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan to Simplified with Mainland idiom.
        /// </summary>
        internal static string tw2sp {
            get {
                return ResourceManager.GetString("tw2sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
