//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCC_GUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_chs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_chs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenCC_GUI.Languages.Language_chs", typeof(Language_chs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空列表.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换文件.
        /// </summary>
        internal static string ConvertFiles {
            get {
                return ResourceManager.GetString("ConvertFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换文本.
        /// </summary>
        internal static string ConvertText {
            get {
                return ResourceManager.GetString("ConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑(&amp;E).
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误消息.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出(&amp;x).
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件(&amp;F).
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港繁体到简体.
        /// </summary>
        internal static string hk2s {
            get {
                return ResourceManager.GetString("hk2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载(&amp;L)....
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体到香港繁体.
        /// </summary>
        internal static string s2hk {
            get {
                return ResourceManager.GetString("s2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体到繁体.
        /// </summary>
        internal static string s2t {
            get {
                return ResourceManager.GetString("s2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体到台湾正体.
        /// </summary>
        internal static string s2tw {
            get {
                return ResourceManager.GetString("s2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体到台湾正体（包括词汇）.
        /// </summary>
        internal static string s2twp {
            get {
                return ResourceManager.GetString("s2twp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换并保存(&amp;S)....
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选(&amp;A).
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选取文件....
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁体到香港繁体.
        /// </summary>
        internal static string t2hk {
            get {
                return ResourceManager.GetString("t2hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁体到简体.
        /// </summary>
        internal static string t2s {
            get {
                return ResourceManager.GetString("t2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁体到台湾正体.
        /// </summary>
        internal static string t2tw {
            get {
                return ResourceManager.GetString("t2tw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台湾正体到简体.
        /// </summary>
        internal static string tw2s {
            get {
                return ResourceManager.GetString("tw2s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台湾正体到简体（包括词汇）.
        /// </summary>
        internal static string tw2sp {
            get {
                return ResourceManager.GetString("tw2sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
